# Generated by Django 5.2.4 on 2025-07-18 09:48

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contact", models.EmailField(max_length=254)),
                ("title", models.CharField(max_length=100, null=True)),
                ("description", models.TextField(null=True)),
                ("salary", models.PositiveIntegerField(null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="jobs/")),
                ("location", models.CharField(max_length=100, null=True)),
                ("company_name", models.CharField(max_length=100, null=True)),
                ("company_description", models.TextField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="title", unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
            },
        ),
        migrations.CreateModel(
            name="JobCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="job_categories/")),
                ("description", models.TextField()),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="title", unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Category",
                "verbose_name_plural": "Job Categories",
            },
        ),
    ]
