# Generated by Django 5.2.4 on 2025-07-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_job_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="contact",
            field=models.CharField(max_length=20),
        ),
    ]
